[variable]
src = "{root}/src"
modules = "{src}/modules"
doctest = "{modules}/doctest"
fmt = "{modules}/fmt"
lua = "{modules}/lua"
# wren = "{modules}/wren"
common_compile_flags = [
    "-fdiagnostics-color=always",
    "-flto",

    "-Wall",
    "-Wextra",
    "-Wshadow",
    "-pedantic",
    "-Wcast-align",
    "-Wunused",
    "-Wconversion",
    "-Wsign-conversion",
    "-Wmisleading-indentation",
    "-Wduplicated-cond",
    "-Wduplicated-branches",
    "-Wlogical-op",
    "-Wnull-dereference",
    "-Wuseless-cast",
    "-Wdouble-promotion",
    "-Wformat=2",
    "-Wimplicit-fallthrough",

    "-D_FORTIFY_SOURCE=2",
    "-D_GLIBCXX_ASSERTIONS",

    "-I {doctest}",
    "-I {fmt}/include",
    "-I {lua}",
    # "-I {wren}/src/include",
]
common_c_flags = ["-xc", "--std=c17", "{common_compile_flags}"]
common_cxx_flags = [
    "-xc++",
    "--std=c++23",
    "{common_compile_flags}",
    "-Wnon-virtual-dtor",
    "-Wold-style-cast",
    "-Woverloaded-virtual",
]
common_ld_flags = [
    "-fdiagnostics-color=always",
    "-flto",

    # "-L {wren}/lib",
    # "-l:libwren.a",
    "-L {lua}",
    "-l:liblua.a",
    "-L {fmt}/build",
    "-l:libfmt.a",
    #
]

[profile.debug]
cflags = [
    "-Og",
    "-g",
    "-fsanitize=address",
    "-fsanitize=undefined",
    "{common_c_flags}",
]
cxxflags = [
    "-Og",
    "-g",
    "-fsanitize=address",
    "-fsanitize=undefined",
    "{common_cxx_flags}",
]
ldflags = [
    "-Og",
    "-g",
    "-fsanitize=address",
    "-fsanitize=undefined",
    "{common_ld_flags}",
    #
]

[profile.optimized]
cflags = [
    "-s",
    "-O3",
    "{common_c_flags}",
    #
]
cxxflags = [
    "-s",
    "-O3",
    "{common_cxx_flags}",
    #
]
ldflags = [
    "-s",
    "-O3",
    "{common_ld_flags}",
    #
]

[binary."quest-on-saer-tor"]
dependencies = [
    "{src}/main.cc",
    #
]
implicit_dependencies = [
    # "{wren}/lib/libwren.a",
    "{lua}/liblua.a",
    "{fmt}/build/libfmt.a",
    #
]
